### ISSUE TITLE
Perfomance of SDK

### ISSUE THREAD

**Issue by n-elloco** [contentful/contentful-management.py#1]
Hello.
We are working with Contentful Management API and we've implemented our own decision before release of yours. One of the essential issues was API perfomance. Now we're learn a possibility to change our solution to yours and we have a suggestion for improving.
In methods, which change state of records in Contentful at the beginning request for change is done and then the method `reload` is called. In fact, this method does additional `get` request to Contentful, which is overhead, because CM API is quite slow. I think, instead of this approach, we can reload instances, based on response of request for change, because this response consist actual version of object.

For example

```python
    def publish(self):
        """Publishes the Resource"""

        response = self._client._put(
            "{0}/published".format(
                self.__class__.base_url(self.sys['space'].id, self.sys['id']),
            ),
            {},
            headers=self._update_headers()
        )

        return self.reload(response)

# ****
    def reload(self, result):
        """Reloads the Resource"""

       if result is None: 
           result = self._client._get(
                self.__class__.base_url(
                    self.sys['space'].id,
                    self.sys['id']
                )
            )

        self._update_from_resource(result)

        return self
```

**Comment by dlitvakb** [comment]
Sounds like a good idea!

I'm currently focused on fixing bugs and improving this SDK, so I will definitely add this!

Cheers

**Comment by dlitvakb** [comment]
PR already created, tomorrow someone from my team will review and it will get merged!

Thanks for the contribution.

**Comment by n-elloco** [comment]
Thank you for improvement. :+1:
