### ISSUE TITLE
Does this SDK support updating editor interfaces? 

### ISSUE THREAD

**Issue by 99littlebugs** [contentful/contentful-management.py#115]
I would like to create new fields that are reference type and use the Entry Cards appearance/editor interface. 

I've tried many variations of save and publish but can't quite get my modifications to save.

**Comment by rubydog** [comment]
@99littlebugs, 

Yes, for detailed guidance on how to update the editor interface, please refer to the documentation provided by Contentful: [Content Management API - Update the Editor Interface](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/editor-interface/editor-interface/update-the-editor-interface/console/python).

If you continue to encounter issues with saving your modifications, please provide more details about the specific errors or behaviors you're experiencing.

Cheers

**Comment by 99littlebugs** [comment]
thanks!
