### ISSUE TITLE
any method to get total number of entries?

### ISSUE THREAD

**Issue by iroth** [contentful/contentful-management.py#13]
I currently iterate through a content type entries by getting a batch (100 entries), advancing the skip parameter and calling again, until I get no more entries.
It would be helpful to get the total number of entries ahead of time to be able to present some progress. I see that in the underlying client.py the total is returned, but it is not exposed to the caller.

**Comment by dlitvakb** [comment]
Hey @iroth,

I'll be adding a wrapper to Contentful's Array just as the CDA SDK has, I'll be pushing it shortly and releasing a new version.

There, you'll have `ct_array.total` or `entry_array.total` to check.

Cheers

**Comment by dlitvakb** [comment]
The change has been merged to `master`, I will finish testing #10 and check if any other changes are required and plan a release for later today.

Cheers
