### ISSUE TITLE
Url Not Valid for Assets

### ISSUE THREAD

**Issue by etienne212** [contentful/contentful-management.py#29]
When I am trying to create an asset with these parameters
{  
   'fields':{  
      'file':{  
         'es':{  
            'url':'http://example.com/sites/default/files/item-es.pdf'
         }
         'en':{
            'url':'http://example.com/sites/default/files/item-en.pdf'
          }
      },
      'title':{  
         'es':'ITEM-ES.pdf',
         'en':'ITEM-EN.pdf'
      },
      'description':{  

      }
   }

I get an invalid url on the asset created, but when i use those same url's through the UI, it works perfectly fine, am i missing some field that needs to be set?

**Comment by dlitvakb** [comment]
Hey @etienne212,

You need to create it like follows:

```python
  'fields': {
        'file': {
            'en-US': {
                'fileName': 'file.png',
                'contentType': 'image/png',
                'upload': 'https://url.to/file.png'
            }
        }
    }
```
