### ISSUE TITLE
Space.uploads().create(file) doesn't work.

### ISSUE THREAD

**Issue by bram-rongen** [contentful/contentful-management.py#52]
It fails with `TypeError: create() missing 1 required positional argument: 'file_or_path'`.

The issue seems to be that space.uploads() returns a `SpaceResourceProxy` to `UploadsProxy` and the `create` method in the `SpaceResourceProxy` is defined like this:
```
    def create(self, resource_id=None, attributes=None):
        """
        Creates a resource with a given ID (optional) and attributes for the current space.
        """

        return self.proxy.create(resource_id=resource_id, attributes=attributes)
```
Where the call indeed doesn't include a positional argument.

**Comment by dlitvakb** [comment]
Merged

Will release a patch version later today.

Thanks for the contribution

**Comment by bram-rongen** [comment]
Thanks for merging this so quickly!
