### ISSUE TITLE
How do you page using this api?

### ISSUE THREAD

**Issue by iroth** [contentful/contentful-management.py#9]
unlike what is written in the readme, the entries.all() various methods return only 100 entries. How one gets the next page?

**Comment by iroth** [comment]
OK, answered myself:
    skip = total = 0
    entries = content_type.entries().all({'skip': skip})
    while len(entries) > 0:
        total += len(entries)
        skip += len(entries)
        entries = content_type.entries().all({'skip': skip})

**Comment by dlitvakb** [comment]
Hey @iroth,

Yes, that's exactly how it's done, the SDK is only an object oriented wrapper to the API, but every SDK call to the API matches 1-to-1 to the API behavior.

Cheers
