### ISSUE TITLE
Bug: Calling content_type.save() appears to wipe out all default values on all fields of the content type

### ISSUE THREAD

**Issue by ghost** [contentful/contentful-management.py#90]
Repro steps:
1. Create a content type with a field with a default value
2. Write a python script that retrieves this content type then calls `content_type.save`
3. Notice that after saving the default value entered in step 1 is empty

Maybe I'm doing something wrong? This seems like a pretty huge bug. I was following exactly the step outlined in `Updating a content type:` in the readme file when I encountered this issue.

**Comment by rubydog** [comment]
Hi!

Thanks for reporting the issue, it is indeed a bug and we are taking a look at it. Will keep you posted on any progress we make in resolving it.

Cheers
